table gold_ui_play_timeline
	lineageTag: b63b7dea-9874-45e3-87e7-c4a306a56d96
	sourceLineageTag: [dbo].[gold_ui_play_timeline]

	measure Draw_Team_Points = ```
			
			VAR Fecha_Corte = CALCULATE(
			    MAX('gold_ui_play_timeline'[Date]),
			    REMOVEFILTERS(gold_dim_race) 
			)
			
			VAR Fecha_Actual = MAX('gold_dim_race'[Date]) 
			
			RETURN
			    IF(
			        NOT(ISFILTERED('gold_ui_play_timeline')),
			        MAX(gold_fact_team_results[Season_Points]),
			
			        IF(
			            Fecha_Actual <= Fecha_Corte,
			            MAX(gold_fact_team_results[Season_Points]),
			            BLANK()
			        )
			    )
			```
		lineageTag: 92e15e54-4da8-4627-9aa6-0241f6d7c581

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		sourceProviderType: datetime2
		lineageTag: a29df72c-3665-4100-8b4b-2cd47e2fd6ed
		sourceLineageTag: Date
		summarizeBy: none
		sourceColumn: Date

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column Race_Key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: c19364ff-a4df-4fc8-bc60-efa97b7ce98f
		sourceLineageTag: Race_Key
		summarizeBy: none
		sourceColumn: Race_Key

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition gold_ui_play_timeline = entity
		mode: directLake
		source
			entityName: gold_ui_play_timeline
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

