table gold_fact_team_results
	lineageTag: 2bf5b417-fe98-4904-807d-8771244f6d17
	sourceLineageTag: [dbo].[gold_fact_team_results]

	measure Puntos_Ranking_Animado = ```
			
			VAR Fecha_Corte = MAX('gold_ui_play_timeline'[Date]) // La fecha del Play Axis
			
			RETURN
			    CALCULATE(
			        // 1. Buscamos el valor acumulado máximo
			        MAX(gold_fact_team_results[Season_Points]), 
			        
			        // 2. FILTRO MÁGICO: Obligamos a Power BI a mirar solo el pasado
			        // "Filtra la tabla de hechos para que solo entren carreras anteriores al corte"
			        gold_dim_race[Date] <= Fecha_Corte
			    )
			```
		lineageTag: e0b18264-39cd-4788-a789-4612b374b430

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Ranking_Oficial_Final = ```
			
			// 1. CAPTURAR LA FECHA DEL PLAY AXIS
			VAR FechaPlay = MAX('gold_ui_play_timeline'[Date])
			VAR HayJuego = ISFILTERED('gold_ui_play_timeline')
			
			// 2. BUSCAR LA ÚLTIMA FECHA REAL CON DATOS (El Freno de Mano) 🛑
			VAR UltimaFechaConDatos = 
			    CALCULATE(
			        MAX(gold_dim_race[Date]),
			        // Solo miramos fechas donde realmente hubo carreras con resultados
			        NOT(ISBLANK(gold_fact_team_results[meeting_key]))
			    )
			
			// 3. DECIDIR LA FECHA DE CORTE (Clamping)
			// Si el Play Axis se va al futuro, nos quedamos en la última carrera real.
			VAR FechaCorte = 
			    IF(
			        HayJuego, 
			        MIN(FechaPlay, UltimaFechaConDatos), 
			        UltimaFechaConDatos
			    )
			
			// 4. LÓGICA DE RECUPERACIÓN (Sin Coalesce)
			VAR UltimoMeetingValido = 
			    CALCULATE(
			        MAX(gold_fact_team_results[meeting_key]),
			        REMOVEFILTERS(gold_dim_race),
			        gold_dim_race[Date] <= FechaCorte
			    )
			
			RETURN
			    // 5. DEVUELVE LA POSICIÓN LIMPIA
			    CALCULATE(
			        MAX(gold_fact_team_results[World_Position]),
			        gold_fact_team_results[meeting_key] = UltimoMeetingValido
			    )
			```
		formatString: 0
		lineageTag: 51edf90a-3a56-49d3-8283-cb5977a22cdf

		changedProperty = Name

	column Year
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 2f4e6dcb-3d9f-4227-9472-2d62c403275a
		sourceLineageTag: Year
		summarizeBy: none
		sourceColumn: Year

		changedProperty = SummarizeBy

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Team ID'
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: b23e3229-bfe3-4352-b736-c5327172e1b7
		sourceLineageTag: Team_ID
		summarizeBy: none
		sourceColumn: Team_ID

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Race_Points
		dataType: double
		isHidden
		sourceProviderType: real
		lineageTag: de566169-56da-4f09-ac68-335c49062100
		sourceLineageTag: Race_Points
		summarizeBy: sum
		sourceColumn: Race_Points

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Season_Points
		dataType: double
		sourceProviderType: real
		lineageTag: 4520f1f0-840a-4bb2-a40e-493fa967cfd3
		sourceLineageTag: Season_Points
		summarizeBy: max
		sourceColumn: Season_Points

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column World_Position
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 6af5e220-9468-4c09-a6a0-4b4e79701ed5
		sourceLineageTag: World_Position
		summarizeBy: none
		sourceColumn: World_Position

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column meeting_key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 35640240-2bbd-4c95-be11-7adacbfb4c2f
		sourceLineageTag: meeting_key
		summarizeBy: none
		sourceColumn: meeting_key

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition gold_fact_team_results = entity
		mode: directLake
		source
			entityName: gold_fact_team_results
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

