table gold_fact_driver_results
	lineageTag: 330adf25-33fe-4187-a313-8246f31e3beb
	sourceLineageTag: [dbo].[gold_fact_driver_results]

	measure Driver_Ranks = ```
			
			VAR UltimaFechaVisible = MAX(gold_dim_race[Date])
			
			VAR UltimoMeeting = 
			    CALCULATE(
			        MAX(gold_fact_driver_results[Race_Key]),
			        gold_dim_race[Date] = UltimaFechaVisible
			    )
			
			RETURN 
			    CALCULATE(
			        MAX(gold_fact_driver_results[World_Position]),
			        gold_fact_driver_results[Race_Key] = UltimoMeeting
			    )
			```
		formatString: 0
		lineageTag: d32c689b-5a38-4861-b639-9d0f25fc0006

		changedProperty = Name

	measure Actual_Team_Logo = ```
			
			VAR FechaCorte = MAX('gold_ui_play_timeline'[Date])
			VAR AnioActual = SELECTEDVALUE('gold_dim_race'[Year])
			
			VAR UltimoMeetingDelPiloto = 
			    CALCULATE(
			        MAX(gold_fact_driver_results[Race_Key]),
			        'gold_dim_race'[Date] <= FechaCorte,
			        'gold_dim_race'[Year] = AnioActual, 
			        REMOVEFILTERS('gold_dim_race'[Date]) 
			    )
			
			VAR TeamID_EnEseMomento = 
			    CALCULATE(
			        MAX(gold_fact_driver_results[Team_Key]),
			        gold_fact_driver_results[Race_Key] = UltimoMeetingDelPiloto,
			        'gold_dim_race'[Year] = AnioActual,
			        REMOVEFILTERS('gold_dim_race'[Date])
			    )
			
			RETURN
			    IF(
			        ISBLANK(UltimoMeetingDelPiloto),
			        BLANK(),
			        CALCULATE(
			            MAX(gold_dim_team[Team_Logo]),
			            gold_dim_team[Team_Key] = TeamID_EnEseMomento
			        )
			    )
			```
		lineageTag: 5533cc63-4c13-4198-824f-6a3f154c240e
		dataCategory: ImageUrl

		changedProperty = Name

		changedProperty = DataCategory

	column Race_Points
		dataType: double
		formatString: " 0.##;;-"
		sourceProviderType: real
		lineageTag: 6831189b-90c7-478f-bed9-d54e9c7bebe2
		sourceLineageTag: Race_Points
		summarizeBy: sum
		sourceColumn: Race_Points

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Season_Points
		dataType: double
		sourceProviderType: real
		lineageTag: 9c2ee9d8-e8fc-492f-8ac0-82cd12efa908
		sourceLineageTag: Season_Points
		summarizeBy: max
		sourceColumn: Season_Points

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column World_Position
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: ea6edaef-cc24-4d6e-82b8-1fe121bfed93
		sourceLineageTag: World_Position
		summarizeBy: none
		sourceColumn: World_Position

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Driver_Key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 32088232-935b-4b2f-b193-d4acbccf3fdd
		sourceLineageTag: Driver_Key
		summarizeBy: none
		sourceColumn: Driver_Key

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Race_Key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 9241ff1b-973a-4f6f-a957-4329c8b1127b
		sourceLineageTag: Race_Key
		summarizeBy: none
		sourceColumn: Race_Key

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Team_Key
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: b06cf934-85eb-4ba2-b86e-2631b41f6939
		sourceLineageTag: Team_Key
		summarizeBy: none
		sourceColumn: Team_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition gold_fact_driver_results = entity
		mode: directLake
		source
			entityName: gold_fact_driver_results
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

