table gold_fact_driver_results
	lineageTag: 330adf25-33fe-4187-a313-8246f31e3beb
	sourceLineageTag: [dbo].[gold_fact_driver_results]

	measure 'Driver Rank Standings' = ```
			
			VAR UltimoMeeting = MAX(gold_fact_driver_results[meeting_key])
			RETURN 
			CALCULATE(
			    MAX(gold_fact_driver_results[World_Position]),
			    gold_fact_driver_results[meeting_key] = UltimoMeeting
			)
			```
		formatString: 0
		lineageTag: d32c689b-5a38-4861-b639-9d0f25fc0006

		changedProperty = Name

	measure Equipo_Actual_Logo = ```
			
			VAR FechaCorte = MAX('gold_ui_play_timeline'[Date])
			VAR AnioActual = SELECTEDVALUE('gold_dim_race'[Year]) // Captura el año del visual o filtro
			
			// 1. Buscamos el último meeting del piloto PERO solo del año actual
			VAR UltimoMeetingDelPiloto = 
			    CALCULATE(
			        MAX(gold_fact_driver_results[meeting_key]),
			        'gold_dim_race'[Date] <= FechaCorte,
			        'gold_dim_race'[Year] = AnioActual, 
			        REMOVEFILTERS('gold_dim_race'[Date]) // Quitamos solo el filtro de fecha específica
			    )
			
			// 2. Recuperamos el ID del equipo en ese momento y año
			VAR TeamID_EnEseMomento = 
			    CALCULATE(
			        MAX(gold_fact_driver_results[Team ID]),
			        gold_fact_driver_results[meeting_key] = UltimoMeetingDelPiloto,
			        'gold_dim_race'[Year] = AnioActual,
			        REMOVEFILTERS('gold_dim_race'[Date])
			    )
			
			// 3. Devolvemos el logo (Solo si hay un meeting encontrado)
			RETURN
			    IF(
			        ISBLANK(UltimoMeetingDelPiloto),
			        BLANK(),
			        CALCULATE(
			            MAX(gold_dim_team[Team Logo]),
			            gold_dim_team[Team ID] = TeamID_EnEseMomento
			        )
			    )
			```
		lineageTag: 5533cc63-4c13-4198-824f-6a3f154c240e
		dataCategory: ImageUrl

		changedProperty = Name

		changedProperty = DataCategory

	column Year
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: d749345d-076c-45fb-98e1-6a827a705dd3
		sourceLineageTag: Year
		summarizeBy: none
		sourceColumn: Year

		changedProperty = SummarizeBy

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Team ID'
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: abadd6f0-bb00-46f3-98bc-19a8d7a98867
		sourceLineageTag: Team_ID
		summarizeBy: none
		sourceColumn: Team_ID

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Race_Points
		dataType: double
		formatString: " 0.##;;-"
		sourceProviderType: real
		lineageTag: 6831189b-90c7-478f-bed9-d54e9c7bebe2
		sourceLineageTag: Race_Points
		summarizeBy: sum
		sourceColumn: Race_Points

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Season_Points
		dataType: double
		sourceProviderType: real
		lineageTag: 9c2ee9d8-e8fc-492f-8ac0-82cd12efa908
		sourceLineageTag: Season_Points
		summarizeBy: max
		sourceColumn: Season_Points

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column World_Position
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: ea6edaef-cc24-4d6e-82b8-1fe121bfed93
		sourceLineageTag: World_Position
		summarizeBy: none
		sourceColumn: World_Position

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column meeting_key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 430f1358-fd86-4c47-bc0f-a065c76dabdc
		sourceLineageTag: meeting_key
		summarizeBy: none
		sourceColumn: meeting_key

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column driver_number
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 158a1ffd-f875-4ede-bbb6-e7d5890df9e3
		sourceLineageTag: driver_number
		summarizeBy: none
		sourceColumn: driver_number

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Driver_Key
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 32088232-935b-4b2f-b193-d4acbccf3fdd
		sourceLineageTag: Driver_Key
		summarizeBy: none
		sourceColumn: Driver_Key

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition gold_fact_driver_results = entity
		mode: directLake
		source
			entityName: gold_fact_driver_results
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

